version: '3.9'

services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - ollama_models:/root/.ollama

    api:
        build: .
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        ports: ['8000:8000']
        environment:
            - OLLAMA_MODEL=mistral
            - OLLAMA_HOST=http://ollama:11434
        depends_on:
            - ollama

volumes:
    ollama_models:
